'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_3ds_Save_Editors_Library.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3DSARG_fdialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3DSARG_fdialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3DSS3DSC_fdialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3DSS3DSC_fdialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3DSSEL_logo_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3DSSEL_logo_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3DSSEL_logo_update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3DSSEL_logo_update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Attack_Potion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attack_Potion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_level() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_level", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EN_area_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EN_area_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EN_area_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EN_area_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EN_area_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EN_area_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EN_area_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EN_area_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EN_area_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EN_area_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EN_area_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EN_area_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EN_arean_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EN_arean_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EN_arean_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EN_arean_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EN_arean_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EN_arean_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EN_arean_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EN_arean_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EN_arean_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EN_arean_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EN_arean_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EN_arean_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EXP_Orb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EXP_Orb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_3DSARG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_3DSARG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_3dssl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_3dssl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_battlegroundz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_battlegroundz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_return() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_return", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_setall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_setall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_update_act() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_update_act", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icon_zombinav_rarezombies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_zombinav_rarezombies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icon_zombinav_weapons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_zombinav_weapons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icon_zombinav_zombies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_zombinav_zombies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info_level() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_level", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property N3DSCS_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N3DSCS_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property N3DSCS_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N3DSCS_icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property N3DSSEL_fdialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("N3DSSEL_fdialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_mainfea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel_mainfea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rzombie_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rzombie_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stamina_Potion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stamina_Potion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property title_3DSSEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("title_3DSSEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_bg_menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_bg_menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_bg_missions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_bg_missions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_bg_panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_bg_panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_fdialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_fdialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_doctorhero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_doctorhero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_hammerhero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_hammerhero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_magehero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_magehero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_misson_cp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_misson_cp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_misson_na() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_misson_na", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_music() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_music", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_rank_bronze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_rank_bronze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_rank_gl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_rank_gl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_rank_gold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_rank_gold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_rank_na() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_rank_na", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_rank_platinium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_rank_platinium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_rank_silver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_rank_silver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_icon_swordhero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_icon_swordhero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_menu_icon_highscores() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_menu_icon_highscores", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_menu_icon_itemsediting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_menu_icon_itemsediting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_menu_icon_lvlareaediting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_menu_icon_lvlareaediting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_menu_icon_missionediting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_menu_icon_missionediting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TKCD_vigor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TKCD_vigor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property weapon_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
